geek_qa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("qa.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # new
]

qa/urls.py
from django.urls import path

from . import views

# define namespace
app_name = "qa"

# Defines URL by string to decide where to send the user
urlpatterns = [
    #path(route, function, name)
    path("", views.index, name="index"),
    # if you go to URL: (name)/employee/(num) to will go to the webpage based
    path("employee/<int:employee_id>", views.employee_page),
    path("error/<int:error_id>", views.get_error, name="view_error"),
    path("create_error", views.create_error),
    path("update_error", views.update_error),
    path("delete_error/<int:error_id>/<path:_next>",
         views.delete_error, name="delete_error"),
    path("search", views.search_errors, name="search")
]

qa/models.py
from datetime import datetime
from django.db import models
from django.utils.translation import gettext as _
from django.utils import timezone

# Create your models here.

# Role refers to the position they hold (i.e. Coordinator, marketing or standard geek)


class Role(models.Model):
    name = models.CharField(_("Name"), max_length=50)

    def __str__(self):
        return self.name

# Tags are associated with errors. One error can have multiple tags (i.e. closing, paperwork etc.)


class Tag(models.Model):
    name = models.CharField(_("Name"), max_length=50)

    def __str__(self):
        return self.name

# Error type refers to a more specific description than tag. It can refer to things like "Late For Work"


class ErrorType(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    severity = models.FloatField(_("Severity"))

    def __str__(self):
        return self.name

# Employee referes to each employee that can be associated with an error. This data will be used for reports


class Employee(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    hire_date = models.DateField(
        _("Hire Date"), auto_now=False, auto_now_add=False
    )
    quit_date = models.DateField(
        _("Leave Date"), auto_now=False, auto_now_add=False, null=True, default=None, blank=True
    )
    roles = models.ManyToManyField("qa.Role", verbose_name=_("Roles"))

    def __str__(self):
        return self.name

# Specifically for errors. Includes all relevant data to an error


class Error(models.Model):
    notes = models.TextField(_("Notes"))
    footprints_number = models.CharField(
        _("FP#"), max_length=10, default=None, blank=True, null=True)
    found_date = models.DateField(
        _("Found Date"), auto_now=False, auto_now_add=False, default=timezone.now
    )
    committed_date = models.DateField(
        _("Committed Date"), auto_now=False, auto_now_add=False, null=True, default=None, blank=True
    )
    type = models.ForeignKey("qa.ErrorType", verbose_name=_(
        "Error Type"), on_delete=models.CASCADE
    )
    employees = models.ForeignKey("qa.Employee", verbose_name=_(
        "Employee"), on_delete=models.CASCADE, related_name="error_employee")
    coordinator = models.ForeignKey("qa.Employee", verbose_name=_(
        "Coordinator"), on_delete=models.CASCADE, related_name="error_coordinator"
    )
    tags = models.ManyToManyField("qa.Tag", verbose_name=_("Tags"))

    @property
    def get_employees(self):
        return ", ".join([e.name for e in self.employees.all()])

qa/views.py
from django.conf.urls import url
from django.db.models import query
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core.serializers import serialize
from django.template import context, loader
from django.template.response import ContentNotRenderedError
from . import models
from datetime import datetime, timedelta
from django.urls import reverse
from pprint import pprint

# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return redirect(reverse("login"))

    template = loader.get_template("qa/index.html.j2")

    error_names_counts = {}
    error_counts_by_day = {}

    queryset = models.Error.objects.order_by('committed_date').all()

    for error in queryset:
        # error count
        error_names_counts.setdefault(error.type.name, 0)
        error_names_counts[error.type.name] += 1

        # error count by week
        key = error.committed_date.strftime("%Y-%m-%d")
        error_counts_by_day.setdefault(key, 0)
        error_counts_by_day[key] += 1

    available_error_types = list(
        models.ErrorType.objects.values("id", "name").order_by("name").all()
    )

    available_employees = list(
        models.Employee.objects.values("id", "name").order_by("name").all()
    )

    available_coordinators = list(
        models.Employee.objects.filter(
            roles__name="Coordinator").values("id", "name").order_by("name").all()
    )

    available_tags = list(
        models.Tag.objects.values("id", "name").order_by("name").all()
    )

    error_count_by_week = get_error_count_by_week()

    week_ranges = []

    sorted_weeks = sorted(list(error_count_by_week.keys()))

    for monday in sorted_weeks:
        monday_dt = datetime.strptime(
            monday, "%Y-%m-%d")
        following_sunday = monday_dt + timedelta(days=6)
        week_ranges.append({
            "start": monday,
            "end": following_sunday.strftime("%Y-%m-%d")
        })

    context = {
        "title": "Home",
        # table
        "errors": models.Error.objects.order_by('-committed_date').all()[:30],

        # pie chart
        'pie_chart_labels': list(error_names_counts.keys()),
        'pie_chart_data': list(error_names_counts.values()),

        # line graph
        "line_graph_labels": sorted_weeks,
        "line_graph_data": [error_count_by_week[week] for week in sorted_weeks],

        # forms
        "available_error_types": available_error_types,
        "available_employees": available_employees,
        "available_coordinators": available_coordinators,
        "available_tags": available_tags,

        # buttons
        "weeks": [week_range for week_range in week_ranges if error_count_by_week[week_range["start"]] > 0],
    }

    return HttpResponse(template.render(context, request))


def employee_page(request, employee_id: int):
    if not request.user.is_authenticated:
        return redirect(reverse("login"))

    employee = models.Employee.objects.filter(id=employee_id).all().first()

    if employee:
        return HttpResponse(employee.name)
    else:
        return HttpResponse("No employee found")


def get_error(request, error_id: int):
    if not request.user.is_authenticated:
        return redirect(reverse("login"))

    e = models.Error.objects.filter(id=error_id).first()

    available_error_types = list(
        models.ErrorType.objects.values("id", "name").all()
    )

    available_employees = list(
        models.Employee.objects.values("id", "name").all()
    )

    available_coordinators = list(
        models.Employee.objects.filter(
            roles__name="Coordinator").values("id", "name").all()
    )

    available_tags = list(
        models.Tag.objects.values("id", "name").all()
    )

    context = {
        "title": f"Error: {e.id}",
        "error": e,
        "formatted_found_date": e.found_date.strftime("%Y-%m-%d"),
        "formatted_committed_date": e.committed_date.strftime("%Y-%m-%d"),
        "available_error_types": available_error_types,
        "available_employees": available_employees,
        "available_coordinators": available_coordinators,
        "available_tags": available_tags
    }
    template = loader.get_template("qa/show_error.html.j2")

    return HttpResponse(template.render(context, request))


def create_error(request):
    if not request.user.is_authenticated:
        return redirect(reverse("login"))

    if request.method == "POST":
        notes = request.POST.get("notes")
        footprints_number = request.POST.get("footprints_number")
        found_date = request.POST.get("found_date")
        committed_date = request.POST.get("committed_date")
        error_type_id = request.POST.get("error_type_id")
        employee_id = request.POST.get("employee_id")
        coordinator_id = request.POST.get("coordinator_id")
        tag_ids = request.POST.getlist("tag_ids")

        print(tag_ids)

        error_type = models.ErrorType.objects.filter(id=error_type_id).first()
        employee = models.Employee.objects.filter(id=employee_id).first()
        coordinator = models.Employee.objects.filter(id=coordinator_id).first()

        tags = []
        for tag_id in tag_ids:
            tags.append(
                models.Tag.objects.filter(id=tag_id).first()
            )

        new_error = models.Error(
            notes=notes,
            footprints_number=footprints_number,
            found_date=found_date,
            committed_date=committed_date,
            type=error_type,
            employees=employee,
            coordinator=coordinator
        )

        new_error.save()

        print(request.POST)

        new_error.tags.set(tags)

    return redirect("/")


def update_error(request):
    if not request.user.is_authenticated:
        return redirect(reverse("login"))

    print(request.POST)

    prev = None

    if request.method == "POST":  # update
        error = models.Error.objects.filter(id=request.POST.get("id")).first()

        notes = request.POST.get("notes")
        footprints_number = request.POST.get("footprints_number")
        found_date = request.POST.get("found_date")
        committed_date = request.POST.get("committed_date")
        error_type_id = request.POST.get("error_type_id")
        employee_id = request.POST.get("employee_id")
        coordinator_id = request.POST.get("coordinator_id")
        tag_ids = request.POST.getlist("tag_ids")

        print(tag_ids)

        error_type = models.ErrorType.objects.filter(id=error_type_id).first()
        employee = models.Employee.objects.filter(id=employee_id).first()
        coordinator = models.Employee.objects.filter(id=coordinator_id).first()

        tags = []
        for tag_id in tag_ids:
            tags.append(
                models.Tag.objects.filter(id=tag_id).first()
            )

        error.notes = notes
        error.footprints_number = footprints_number
        error.found_date = found_date
        error.committed_date = committed_date
        error.type = error_type
        error.employees = employee
        error.coordinator = coordinator

        error.save()

        print(request.POST)

        error.tags.set(tags)

        prev = request.POST.get("prev")
        print(f"PREV TYPE: {type(prev)}")

    return redirect(prev if prev else "/")


def delete_error(request, error_id, _next):
    if not request.user.is_authenticated:
        return redirect(reverse("login"))

    error = models.Error.objects.filter(id=error_id).first()
    error.delete()

    return redirect(_next)


def get_error_count_by_week(query=None):

    # https://stackoverflow.com/questions/8746014/django-group-by-date-day-month-year

    from django.db.models.functions import TruncWeek
    from django.db.models import Count
    from datetime import datetime

    if not query:
        query = models.Error.objects.all()

    queryset = list(
        query
        .annotate(week=TruncWeek("committed_date"))
        .values("week")
        .annotate(c=Count("id"))
        .values("week", "c")
    )

    weeks = set([k['week'] for k in queryset])
    dict3 = []
    for week in weeks:
        temp_val = []
        for dict_ in queryset:
            if dict_['week'] == week:
                temp_val.append(dict_['c'])
        dict3.append({'week': week, 'c': sum(temp_val)})
    pprint(dict3)

    queryset = dict3

    # if query:

    # else:
    #     queryset = list(
    #         models.Error.objects
    #         .annotate(week=TruncWeek("committed_date"))
    #         .values("week")
    #         .annotate(c=Count("id"))
    #         .values("week", "c")
    #     )

    # [{"week": dt, "c": n}]

    # pprint(queryset)

    week_counts = {}

    if len(queryset) > 0:

        for data in queryset:
            key = data["week"].strftime("%Y-%m-%d")
            value = data["c"]

            week_counts[key] = value

        weeks_dt = [datetime.strptime(week, "%Y-%m-%d")
                    for week in week_counts.keys()]

        start_date = min(weeks_dt)
        end_date = max(weeks_dt)

        while start_date < end_date:
            week_counts.setdefault(
                start_date.strftime("%Y-%m-%d"),
                0
            )
            start_date += timedelta(days=7)

    return week_counts


def search_errors(request):
    if not request.user.is_authenticated:
        return redirect(reverse("login"))

    from django.utils.datastructures import MultiValueDictKeyError

    # gets list of every error
    # errors = models.Error.objects.all()
    errors = models.Error.objects

    # get tag names from URL
    tag_names = request.GET.getlist("tags")
    # Get data from database
    tags = models.Tag.objects.filter(name__in=tag_names)

    # filter out errors that dont have specified tags via loop
    for tag in tags:
        errors = errors.filter(tags__id=tag.id)

    start_date_str = request.GET.get("start")

qa/templates/qa/index.html.j2
{% extends 'qa/base.html.j2' %} {% block styles %}
<style>
  .row {
    padding: 10px;
    border: 1px black solid;
    border-radius: 5px;
  }

  .modal-chart {
    max-height: 100%;
  }
</style>
{% endblock styles %} {% block content %}

<div class="row my-3">
  <div class="col-md-6 d-flex justify-content-md-start">
    <h1>EKU IT Geeks QA</h1>
  </div>
  <div class="col-md-6 d-flex justify-content-md-end">
    <a href="{% url 'qa:search' %}" class="btn btn-primary btn-lg mx-2 d-flex justify-content-center align-items-center">
      Search
    </a>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg mx-2" data-bs-toggle="modal" data-bs-target="#logErrorModal">
      Log New Error
    </button>
  </div>
</div>

{# CHARTS #}
<div class="row my-3">
  <div class="col-lg-6 my-3">
    <canvas data-bs-toggle="modal" data-bs-target="#pieChartModal" id="pie-chart"></canvas>
  </div>
  <div class="col-lg-6 my-3">
    <canvas data-bs-toggle="modal" data-bs-target="#lineChartModal" id="line-chart"></canvas>
  </div>
</div>

{# TABLE #}
<div class="row my-3">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th scope="col">Geek Name</th>
        <th scope="col">Error Type</th>
        <th scope="col">Commit Date</th>
        <th scope="col">Date Found</th>
      </tr>
    </thead>
    <tbody>
      {% for e in errors %}
      <tr data-id="{{ e.id }}" data-href="{% url 'qa:view_error' e.id %}" class="clickable-row">
        <td>{{ e.employees }}</td>
        <td>{{ e.type.name }}</td>
        <td>{{ e.committed_date }}</td>
        <td>{{ e.found_date }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<!-- add error modal -->
<div class="modal fade" id="logErrorModal" tabindex="-1" aria-labelledby="logErrorModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <form action="/create_error" method="POST">
        <div class="modal-header">
          <h5 class="modal-title" id="logErrorModalLabel">Log New Error</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" style="max-height: 500px; overflow: auto !important;">
          {% csrf_token %}
          <!-- Notes -->
          <div class="form-group">
            <label for="notesInput">Notes</label>
            <textarea
              class="form-control"
              id="notesInput"
              name="notes"
              placeholder="Please provide a brief description of the error"
            ></textarea>
          </div>

          <!-- FP# -->
          <div class="form-group">
            <label for="fpInput">FP#</label>
            <input
              type="text"
              class="form-control"
              id="fpInput"
              name="footprints_number"
              placeholder="12345"
            />
          </div>

          <!-- Found Date -->
          <div class="form-group">
            <label for="dateFoundInput">Date Found</label>
            <input
              type="date"
              class="form-control default-today"
              id="dateFoundInput"
              name="found_date"
            />
          </div>

          <!-- Committed Date -->
          <div class="form-group">
            <label for="dateCommittedInput">Date Committed</label>
            <input
              type="date"
              class="form-control default-today"
              id="dateCommittedInput"
              name="committed_date"
            />
          </div>

          <!-- Error Type -->
          <div class="form-group">
            <label for="errorTypeInput">Error Type</label>
            <select class="form-control" id="errorTypeInput" name="error_type_id">
            <option selected></option>
              {% for error_type in available_error_types %}
              <option value="{{ error_type.id }}">{{ error_type.name }}</option>
              {% endfor %}
            </select>
          </div>

          <!-- Employee -->
          <div class="form-group">
            <label for="employeeInput">Employee</label>
            <select class="form-control" id="employeeInput" name="employee_id">
            <option selected></option>
              {% for employee in available_employees %}
              <option value="{{ employee.id }}">{{ employee.name }}</option>
              {% endfor %}
            </select>
          </div>

          <!-- Coordinator -->
          <div class="form-group">
            <label for="coordinatorInput">Coordinator</label>
            <select class="form-control" id="coordinatorInput" name="coordinator_id">
            <option selected></option>
              {% for coordinator in available_coordinators %}
              <option value="{{ coordinator.id }}">{{ coordinator.name }}</option>
              {% endfor %}
            </select>
          </div>

          <!-- Tags -->
          <div class="form-group">
            <label for="tagInput">Tags</label>
            <select
              multiple
              class="form-control"
              id="tagInput"
              name="tag_ids"
              aria-describedby="tagHelp"
            >
              {% for tag in available_tags %}
              <option value="{{ tag.id }}">{{ tag.name }}</option>
              {% endfor %}
            </select>
            <small id="tagHelp" class="form-text text-muted">
              Hold CTRL to select multiple tags
            </small>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

{# pie chart modal #}

<!-- Modal -->
<div class="modal fade show" id="pieChartModal" tabindex="-1" aria-hidden="true" role="dialog">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <canvas class="modal-chart" id="pie-chart-large"></canvas>
      </div>
    </div>
  </div>
</div>

{# line chart modal #}
<div class="modal fade show" id="lineChartModal" tabindex="-1" aria-hidden="true" role="dialog">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <canvas class="modal-chart" id="line-chart-large"></canvas>
      </div>
    </div>
  </div>
</div>


{# CREATE BUTTON FOR EACH WEEK #}

{% for week in weeks %}
  <a href="{% url 'qa:search' %}?start={{ week.start }}&end={{ week.end }}" class="btn btn-primary mt-2 mb-3">{{ week.start }}</a>
{% endfor %}

{% endblock content %} {% block scripts %}
{% load static %}
<script src="{% static 'qa/js/moment.min.js' %}"></script>

<script>
  window.addEventListener("load", () => {
    // make table rows clickable
    document.querySelectorAll(".clickable-row").forEach(row => {
      row.addEventListener("click", () => {
        window.location = row.dataset.href
      })
    })
  })

  // set date picker default to today
  var today = moment().format('YYYY-MM-DD');
  document.querySelectorAll(".default-today").forEach(_input =>{
    _input.value = today;
  })

  // PIE CHART
  function getRandomColor() {
    return `#${Math.floor(Math.random() * 16777215).toString(16)}`
  }

backgroundColors = ['#AA0000', '#0000AA', '#00AA00', '#01cdfe', '#90400A','#dfdb76','#b99df0',
                      '#046e6c', '#c6d9e9', '#fbd11d', '#904f0f', '#ffb3ba','#bae1ff','#baffc9',
                      '#ff71ce', '#b967ff', '#01cdfe', '#05ffa1', '#f3c9bd','#00AA88'];
  
  const pie_chart_labels = {{ pie_chart_labels| safe }}
  const pie_chart_data = {{ pie_chart_data| safe }}

  const loopToThisNumber = pie_chart_labels.length - backgroundColors.length;

  for (let i = 0; i < loopToThisNumber; i += 1) {
    backgroundColors.push(getRandomColor())
  };

  var config = {
    type: 'pie',
    data: {
      datasets: [{
        data: pie_chart_data,
        backgroundColor: backgroundColors,
        label: 'Type of Error Comparison'
      }],
      labels: pie_chart_labels
    },
    options: {
      responsive: true
    }
  };

  var ctx = document.getElementById('pie-chart-large').getContext('2d');
  window.myPie3 = new Chart(ctx, config);
  
  // PIE CHART large

  config2 = {
    ...config,
    options: {
      responsive: true,
      legend: {
        onClick: null  
      }
    }
  }

  var ctx = document.getElementById('pie-chart').getContext('2d');
  window.myPie1 = new Chart(ctx, config2);

  

  // Line chart
  const line_graph_labels = {{ line_graph_labels | safe}}
  const line_graph_data = {{ line_graph_data | safe}}

  var config = {
    type: "line",
    data: {
      datasets: [
        {
          data: line_graph_data,
          backgroundColor: backgroundColors,
          label: "Error Count by Week",
          fill: false,
          borderColor: "#000000",
        },
      ],
      labels: line_graph_labels,
    },
    options: {
      responsive: true,
      hover: {
        mode: 'label'
      },
      scales: {
        yAxes: [{
          display: true,
          ticks: {
            beginAtZero: true
          }
        }]
      },
    }
  };

  var ctx = document.getElementById("line-chart-large").getContext("2d");
  window.myPie2 = new Chart(ctx, config);

  config2 = {
    ...config,
    options: {
      responsive: true,
      legend: {
        onClick: null  
      }
    }
  }

  var ctx = document.getElementById("line-chart").getContext("2d");
  window.myPie2 = new Chart(ctx, config2);

  var testtest = {{ testtest | safe }}
  console.log(testtest)
</script>
{% endblock scripts %}

qa/templates/qa/show_error.html.j2
{% extends 'qa/base.html.j2' %}

{% block content %}

  <a
  {% ifequal request.build_absolute_uri request.META.HTTP_REFERER %}
    href="{% url 'qa:index' %}"
  {% else %}
    href="{{ request.META.HTTP_REFERER }}"
  {% endifequal %}
    class="btn btn-primary mb-3"
  >
    Back
  </a>

  <form action="/update_error" method="POST">
    {% csrf_token %}

    <input type="text" name="id" id="errorId" value="{{ error.id }}" hidden>
    <input type="text" name="prev" id="prev" value="{{ request.META.HTTP_REFERER }}" hidden>

    <!-- Notes -->
    <div class="form-group">
      <label for="notesInput">Notes</label>
      <textarea
        class="form-control"
        id="notesInput"
        name="notes"
        placeholder="Please provide a brief description of the error"
        disabled
      >{{ error.notes }}</textarea>
    </div>

    <!-- FP# -->
    <div class="form-group">
      <label for="fpInput">FP#</label>
      <input
        type="text"
        class="form-control"
        id="fpInput"
        name="footprints_number"
        placeholder="12345"
        {% if error.footprints_number != None %}
            value="{{ error.footprints_number }}"
        {% endif %}
        disabled
      />
    </div>

    <!-- Found Date -->
    <div class="form-group">
      <label for="dateFoundInput">Date Found</label>
      <input
        type="date"
        class="form-control"
        id="dateFoundInput"
        name="found_date"
        value="{{ formatted_found_date }}"
        disabled
      />
    </div>

    <!-- Committed Date -->
    <div class="form-group">
      <label for="dateCommittedInput">Date Committed</label>
      <input
        type="date"
        class="form-control"
        id="dateCommittedInput"
        name="committed_date"
        value="{{ formatted_committed_date }}"
        disabled
      />
    </div>

    <!-- Error Type -->
    <div class="form-group">
      <label for="errorTypeInput">Error Type</label>
      <select class="form-control" id="errorTypeInput" name="error_type_id" disabled>
        {% for error_type in available_error_types %}
        <option
            value="{{ error_type.id }}"
            {% ifequal error_type.id error.type.id %}
                selected
            {% endifequal %}
        >
            {{ error_type.name }}
        </option>
        {% endfor %}
      </select>
    </div>

    <!-- Employee -->
    <div class="form-group">
      <label for="employeeInput">Employee</label>
      <select class="form-control" id="employeeInput" name="employee_id" disabled>
        {% for employee in available_employees %}
        <option
            value="{{ employee.id }}"
            {% ifequal employee.id error.employees.id %}
                selected
            {% endifequal %}
        >
            {{ employee.name }}
        </option>
        {% endfor %}
      </select>
    </div>

    <!-- Coordinator -->
    <div class="form-group">
      <label for="coordinatorInput">Coordinator</label>
      <select class="form-control" id="coordinatorInput" name="coordinator_id" disabled>
        {% for coordinator in available_coordinators %}
        <option
            value="{{ coordinator.id }}"
            {% ifequal coordinator.id error.coordinator.id %}
                selected
            {% endifequal %}
        >
                {{ coordinator.name }}
        </option>
        {% endfor %}
      </select>
    </div>

    <!-- Tags -->
    <div class="form-group">
      <label for="tagInput">Tags</label>
      <select
        multiple
        class="form-control"
        id="tagInput"
        name="tag_ids"
        aria-describedby="tagHelp"
        disabled
      >
        {% for tag in available_tags %}
        <option
            value="{{ tag.id }}"
            {% if tag in error.tags.values.all %}
                selected
            {% endif %}
        >
            {{ tag.name }}
        </option>
        {% endfor %}
      </select>
      <small id="tagHelp" class="form-text text-muted">
        Hold CTRL to select multiple tags
      </small>
    </div>

    <br />

    <button type="button" style="display: none;" class="btn btn-secondary" id="cancelBtn">Cancel</button>
    <button type="submit" style="display: none;" class="btn btn-success" id="updateBtn">Update</button>
    <button type="button" class="btn btn-warning" id="editBtn">Edit</button>

    <!-- Button trigger modal -->
    <button type="button" style="display: none;" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal" id="deleteBtn">
      Delete
    </button>
  </form>
   
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this error?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <a href="{% url 'qa:delete_error' error_id=error.id _next=request.META.HTTP_REFERER %}" class="btn btn-danger">Delete</a>
        </div>
      </div>
    </div>
  </div>


    
{% endblock content %}

{% block scripts %}
    <script>
      const updateBtn = document.querySelector("#updateBtn");
      const editBtn = document.querySelector("#editBtn");
      const cancelBtn = document.querySelector("#cancelBtn");
      const deleteBtn = document.querySelector("#deleteBtn");

      const _textarea = document.querySelector("textarea");
      const inputs = document.querySelectorAll("input.form-control");
      const selects = document.querySelectorAll("select.form-control");

      window.addEventListener("load", () => {
        editBtn.addEventListener("click", () => {
          inputs.forEach(_input => {
            _input.disabled = false;
          })

          selects.forEach(_select => {
            _select.disabled = false;
          })

          _textarea.disabled = false;

          editBtn.style.display = "none";
          updateBtn.style.display = "inline";
          cancelBtn.style.display = "inline";
          deleteBtn.style.display = "inline";
        })

        cancelBtn.addEventListener("click", () => {
          location.reload(true);
        })
      })
    </script>
{% endblock scripts %}